### PR TITLE
Added promise support

### PR DESCRIPTION
**Pull request by malexdev**
Added promise support for hash generation. 
Tried to keep code style roughly the same, and used < ES 2015 like the rest of the file. 
Tests show as passing.

### CODE REVIEW

**Comment by quocnguyen** [comment]
IMO this is a bit overkill, why not using promisify, for example gabmontes/tiny-promisify is a good one.

**Comment by malexdev** [comment]
It could use something like that, but I didn't want to add a dependency
where it really isn't needed.

**Comment by quocnguyen** [comment]
Actually your code  look good to me. I would love to merge it. But it can be better if you could update your comment style to follow the old style .

And maybe add more examples to readme, you know, tell the audience your new feature.

**Comment by malexdev** [comment]
Good points. 

I'll plan to address that tonight. 


Alex






On Fri, Jul 22, 2016 at 10:27 PM -0500, "quocnguyen" <notifications@github.com> wrote:












Actually your code  look good to me. I would love to merge it. But it can be better if you could update your comment style to follow the old style .



And maybe add more examples to readme, you know, tell the audience your new feature.

**Comment by malexdev** [comment]
@quocnguyen Finally made those changes, sorry that "tonight" actually meant "9 days from now" :smile:

**Comment by malexdev** [comment]
Also realized I was missing a test, added that.

**Pull request merged**
